### ISSUE TITLE
codesign segfault?

### ISSUE THREAD

**Issue by vtjnash** [JuliaCI/julia-buildbot#135] opened 2019-10-25 20:01 UTC
I'm not even sure what to make of this:
https://build.julialang.org/#/builders/73/builds/5889
```
rm -fr /Users/sabae/buildbot/worker/package_macos64/build/julia-7b826bab47
tar zxf /Users/sabae/buildbot/worker/package_macos64/build/julia-7b826bab47-mac64.tar.gz -C dmg/Julia-1.4.app/Contents/Resources/julia --strip-components 1
if [ -n "$MACOS_CODESIGN_IDENTITY" ]; then \
	    echo "Codesigning with identity $MACOS_CODESIGN_IDENTITY"; \
		codesign -s "$MACOS_CODESIGN_IDENTITY" -v --deep dmg/Julia-1.4.app; \
	else \
		true; \
	fi
Codesigning with identity 2053E9292809B66582CA9F042B470C0929340362
/bin/sh: line 1: 82745 Segmentation fault: 11  codesign -s "$MACOS_CODESIGN_IDENTITY" -v --deep dmg/Julia-1.4.app
make[1]: *** [dmg/Julia-1.4.app] Error 139
```
@staticfloat

**Comment by vtjnash** [comment] 2019-10-29 14:42
Still happening: https://build.julialang.org/#/builders/73/builds/6037

**Comment by staticfloat** [comment] 2019-10-29 18:15
They both happened on the same worker; I've installed some updates and rebooted the machine.  Beyond that, I haven't been able to reproduce on the machine manually.

**Comment by vtjnash** [comment] 2019-11-01 20:11
Still happening: https://build.julialang.org/#/builders/73/builds/6154 (same machine)

**Comment by vtjnash** [comment] 2019-11-01 21:28
Another possible instance, but this time with an error message:
```
dmg/Julia-1.4.app: A timestamp was expected but was not found.
```
https://build.julialang.org/#/builders/73/builds/6161

**Comment by staticfloat** [comment] 2019-11-01 22:49
Looks like that can be due to network issues: https://forums.developer.apple.com/thread/8187

**Comment by staticfloat** [comment] 2019-11-14 07:21
Fixed by wiping out `akatsuki`, which has now been reborn as `macmini3`.  It also faced its fair share of issues, but seems to be working now.

**Closed by staticfloat** 2019-11-14 07:21 UTC
